### ISSUE TITLE
Question: Is there a way to make soletta-dev-app to be run on system V?

### ISSUE THREAD

**Issue by fulong82** [solettaproject/soletta-dev-app#142]
Hi @brunobottazzini, @kamidipreetham, @bdilly & @barbieri 

Since Yocto project allows to choose which init system to be used on their end image and it may have difficulty for the other/legacy components converting to systemd. So, we would like to find out is it possible for soletta-dev-app to break the dependency on systemd and make it support on system V as well?  

Thanks & Regards,
Wilson
@laykuanloon, @lblim, @elvinongbl, @joyceooi295

**Comment by lblim** [comment]
@brunobottazzini, @kamidipreetham, @bdilly & @Barbieri

One of our BSP does not POR systemd, so soletta-dev-app will not be able to run.

**Comment by lblim** [comment]
We have dropped Soletta-dev-app, will integrate it again when the BSP switch to systemd.

**Comment by lblim** [comment]
@fulong82 Please close this ticket

**Comment by barbieri** [comment]
currently we use systemd to start the fbp runner in a controlled environment. One could offer an alternative version that instead would use nodejs and directly call the script, monitoring its lifetime.  We also integrate with journald to show logs... thus it's better to keep using systemd.

systemd may look bigger and more complex than sysv initd, but it's actually not. Particularly if you account a reasonable system with dynamic behavior, to achieve with sysvinit is a pain, like hotplug events.

**Comment by fulong82** [comment]
Okay. Noted. Thanks.
Closing this ticket.
