### ISSUE TITLE
Change code highlight colors or line error background color

### ISSUE THREAD

**Issue by bdilly** [solettaproject/soletta-dev-app#23]
Contrast is bad for lines with errors, so I can't read it in order to fix the problem.
Maybe a better background color for lines with error could be used, or change code highlight colors in case of error.

**Comment by brunobottazzini** [comment]
As suggested, I have made some changes in the color. You can see in the PR https://github.com/solettaproject/soletta-dev-app/pull/33

@bdilly, What do you think of this color?
![screenshot from 2015-09-28 15 57 20](https://cloud.githubusercontent.com/assets/4460234/10145563/2ca40f56-65fa-11e5-812e-29aa89a37190.png)

**Comment by bdilly** [comment]
@brunobottazzini much better =D

**Comment by brunobottazzini** [comment]
Thank you !

PR merged and issue closed
