### ISSUE TITLE
Do not overwrite samples automatically

### ISSUE THREAD

**Issue by bdilly** [solettaproject/soletta-dev-app#24]
After I made a change in a sample, load another, and return to previous one I was expecting it to load original sample again. Instead, it load the modified version. Even after syncing with the repo again, what takes ages to be completed, I wasn't able to load original version.

**Comment by brunobottazzini** [comment]
@bdilly, I have made some change in the color as suggested as you can see in the PR https://github.com/solettaproject/soletta-dev-app/pull/33

What do you think of this color?
![screenshot from 2015-09-28 15 57 20](https://cloud.githubusercontent.com/assets/4460234/10145563/2ca40f56-65fa-11e5-812e-29aa89a37190.png)

**Comment by brunobottazzini** [comment]
PR opened for this task: https://github.com/solettaproject/soletta-dev-app/pull/35

**Comment by brunobottazzini** [comment]
Merged with master branch
