### ISSUE TITLE
DECLARE include with relative path is not working

### ISSUE THREAD

**Issue by otaviobp** [solettaproject/soletta-dev-app#57]
DECLARE=Node:fbp:node_file.fbp won't work when using relative paths.
This is happening because dev-app is moving the fbp file to /tmp before running it. The ideal is to run sol-fbp-runner in the development path.

**Comment by brunobottazzini** [comment]
Fix proposed: https://github.com/solettaproject/soletta-dev-app/pull/71

**Comment by brunobottazzini** [comment]
Fix integrated thanks :+1:
