### ISSUE TITLE
Button shows "Code copied to Clipboard" but no code can be pasted in Cheat Sheet

### ISSUE THREAD

**Issue by preetham** [solettaproject/soletta-dev-app#62]
In Cheat Sheet, several example codes are displayed but the button which says "Get Code" isn't actually copying code to the clipboard.

![screenshot from 2016-03-15 20-45-37](https://cloud.githubusercontent.com/assets/9149028/13782918/2910beb4-eaef-11e5-8588-65f8496ed850.png)

**Comment by brunobottazzini** [comment]
Just tested also and the issue was fixed
http://solettaproject.github.io/docs/nodetypes

Thanks :D
