### ISSUE TITLE
highlight syntax: uppercase var name is blue

### ISSUE THREAD

**Issue by brunobottazzini** [solettaproject/soletta-dev-app#66]
The R from RotaryAngleSensor shouldn't be blue, only the nodetypes and the ports

![screenshot from 2016-03-17 14 26 23](https://cloud.githubusercontent.com/assets/4460234/13854901/8ce2bbf0-ec4c-11e5-991e-f56bb1d50266.png)

**Comment by barbieri** [comment]
actually, RotaryangleSensor is a type name, so it all should be in blue :-)

Same for `LCDString`, not just `LCD`, but the whole `LCDString`

to me looks like an incorrect regexp, likely it should be:

```
[(]([^:)]+)[:)]
```

That is: after the parenthesis `[(]` you create a group of more than one character that are not `)`or `:`, that is `([^:)]+)`, then ends with `)` or `:` as terminators

**Comment by brunobottazzini** [comment]
Yes! Makes sense.

I will test this regexp thanks

**Comment by brunobottazzini** [comment]
Fix proposed: https://github.com/solettaproject/soletta-dev-app/pull/68

Thanks the regexp worked really well :+1:

**Comment by brunobottazzini** [comment]
Fixed with patch -> https://github.com/solettaproject/soletta-dev-app/pull/69/
