### ISSUE TITLE
SVG image not displayed for several nodetypes

### ISSUE THREAD

**Issue by preetham** [solettaproject/soletta-dev-app#73]
After clicking "See Example" svg image of the code is not displayed for following nodetypes attached in the text file.
[result.txt](https://github.com/solettaproject/soletta-dev-app/files/206922/result.txt)
For all these entries exampleList[] was empty in index.html js script (for creating new entries).
![screenshot from 2016-04-05 13-21-48](https://cloud.githubusercontent.com/assets/9149028/14274944/ebf1e758-fb31-11e5-9c43-ca57825860e2.png)
![screenshot from 2016-04-05 13-23-58](https://cloud.githubusercontent.com/assets/9149028/14274945/ebf5286e-fb31-11e5-8ce3-9eff2660ef53.png)

**Comment by brunobottazzini** [comment]
Issue fixed in PR: https://github.com/solettaproject/soletta/pull/2188
