### ISSUE TITLE
The server port 80 in configuration.json does not take effect. server always use port 8080.

### ISSUE THREAD

**Issue by otcyanglei** [solettaproject/soletta-dev-app#80]
current configuration.json set the server port to 80. However, the soletta-dev-app server keep listening port 8080, regardless what I set in configuration.json. 

Environment: v1_beta7

**Comment by brunobottazzini** [comment]
The next version that will be released today will contain this fix.

The commit that fix is this one: https://github.com/solettaproject/soletta-dev-app/commit/540e00f0147edb59c6b3f328874cab708c6d4e9d

**Comment by brunobottazzini** [comment]
Patch merged and issue fixed...

Thanks
