### ISSUE TITLE
Flow from previous sample is displayed on wrong flows

### ISSUE THREAD

**Issue by bdilly** [solettaproject/soletta-dev-app#92]
When moving from a correct flow (that draws a flow) to a previously saved faulty flow (that doesn't generate a flow), the previous one kept drawn on the flow view.

Steps to reproduce:
- Save a file that doesn't generates a flow
- Go to a demo sample
- Go back to wrong file

**Comment by brunobottazzini** [comment]
Fix proposed: https://github.com/solettaproject/soletta-dev-app/pull/94

**Comment by brunobottazzini** [comment]
As fix #94 was declined, I have proposed a V2 for it: https://github.com/solettaproject/soletta-dev-app/pull/101

Difference between commits is the way it was being cleared the SVG.

Could you test it ?

**Comment by preetham** [comment]
This bug shows even when an older correct flow file is in the editor, if a new file is created and we switch to it. Fix #101  by @brunobottazzini corrects this.

**Comment by brunobottazzini** [comment]
@kamidipreetham thanks for the review... merged and issue solved...
